added open/hide calendar
snizhanamohyl/team-proj-news-app pull request #12
Opened 2023-02-18 21:15 UTC by MatokhniukA

2023-02-18 23:00 UTC, snizhanamohyl requested changes

2023-02-18 23:00 UTC, snizhanamohyl commented on src/sass/components/_calendar.scss
> +    @media screen and (min-width: $desktop) {
спробуй @media screen and (min-width: $desktop) замінити на @include desktop

2023-02-18 23:00 UTC, snizhanamohyl commented on src/sass/components/_calendar.scss
> +    gap: 13px;
наче якщо прибрати gap нічого не полетить. у тебе ж все рівномірно має стати завдяки justify-content: space-between;

2023-02-18 23:00 UTC, snizhanamohyl commented on src/sass/components/_calendar.scss
> +    height: 34px;
висота така і буде завдяки падінгам по ідеї, height: 34px; наче можна прибрати, чекни)

2023-02-18 23:00 UTC, snizhanamohyl commented on src/sass/components/_calendar.scss
> +    @media screen and (min-width: $tablet) {
@media screen and (min-width: $tablet) -> @include tablet

2023-02-18 23:00 UTC, snizhanamohyl commented on src/sass/components/_calendar.scss
> +        gap: 18px;
а навіщо gap?

2023-02-18 23:00 UTC, snizhanamohyl commented on src/sass/components/_calendar.scss
> +    margin-left: 12px;
наче марджини не грають ролі з position: absolute;

2023-02-18 23:00 UTC, snizhanamohyl commented on src/sass/components/_calendar.scss
> +    margin-left: 12px;
знову ж таки марджин при position: absolute; не потрібен, перевір

2023-02-18 23:00 UTC, snizhanamohyl commented on src/sass/components/_calendar.scss
> +    padding: 7px 0px;
перевір падінги, я бачу тут 11px по вертикалі

2023-02-18 23:00 UTC, snizhanamohyl commented on src/sass/components/_calendar.scss
> +    height: 44px;
height по ідеї від падінгів підтягнеться

2023-02-18 23:00 UTC, snizhanamohyl commented on src/sass/components/_calendar.scss
> +    &:nth-last-child(-n + 7) {
а тут завжди останній ряд складатиметься з 7 елементів? якщо місяць закінчується посеред тижня і далі дні не будуть прописуватися, то їх буде не 7.
чи ми дні прописуємо завжди, щоб заповнити рядок повністю?

2023-02-19 09:19 UTC, MatokhniukA commented on src/sass/components/_calendar.scss
> +    @media screen and (min-width: $desktop) {
виправила

2023-02-19 09:19 UTC, MatokhniukA commented on src/sass/components/_calendar.scss
> +    gap: 13px;
виправила

2023-02-19 09:19 UTC, MatokhniukA commented on src/sass/components/_calendar.scss
> +    height: 34px;
виправила

2023-02-19 09:19 UTC, MatokhniukA commented on src/sass/components/_calendar.scss
> +    @media screen and (min-width: $tablet) {
виправила

2023-02-19 09:19 UTC, MatokhniukA commented on src/sass/components/_calendar.scss
> +        gap: 18px;
виправила

2023-02-19 09:20 UTC, MatokhniukA commented on src/sass/components/_calendar.scss
> +    margin-left: 12px;
треба залишити, бо з"їжджає іконка

2023-02-19 09:23 UTC, MatokhniukA commented on src/sass/components/_calendar.scss
> +    margin-left: 12px;
виправила

2023-02-19 09:27 UTC, MatokhniukA commented on src/sass/components/_calendar.scss
> +    padding: 7px 0px;
виправила

2023-02-19 09:27 UTC, MatokhniukA commented on src/sass/components/_calendar.scss
> +    height: 44px;
виправила

2023-02-19 09:30 UTC, MatokhniukA commented on src/sass/components/_calendar.scss
> +    &:nth-last-child(-n + 7) {
рядок завжди буде повний, бо буде продовження числами з наступного місяця

2023-02-19 20:00 UTC, snizhanamohyl approved these changes

2023-02-19 20:11 UTC, merged