Feature/favorites
snizhanamohyl/team-proj-news-app pull request #14
Opened 2023-02-19 11:46 UTC by uvchuk

add dark styles to mobile menu, upgrade favorites script

2023-02-19 14:02 UTC, snizhanamohyl reviewed
notiflix можна потім реалізувати, ще видали у себе файли з розширенням css, css.map у папці sass, щоб потім не було конфліктів

2023-02-19 14:02 UTC, snizhanamohyl commented on src/favorite.js
> +const savedFavorites = localStorage.getItem('Favorites');
мабуть назви ключ в localStorage з маленької літери

2023-02-19 14:02 UTC, snizhanamohyl commented on src/favorite.js
> +    getCardsRef();
ти тут типу витягуєш нові рефи, щоб відстежити зміну класу по кнопці? а воно піде в глобальні змінні?

2023-02-19 14:02 UTC, snizhanamohyl commented on src/favorite.js
> +    console.log('Saved news cards in favorite: ', favoriteCardsArray.length);
консоль логів потім не буде, помилку можна буде замінити на сповіщення бібліотеки notiflix

2023-02-19 14:02 UTC, snizhanamohyl commented on src/favorite.js
> +    console.log('Failed to markup your favorites news');
notiflix

2023-02-19 14:02 UTC, snizhanamohyl commented on src/js/dark-theme.js
> +const currentTheme = localStorage.getItem('CurrentPageTheme');
ключ в localStorage називай по типу current-page-theme

2023-02-19 14:02 UTC, snizhanamohyl commented on src/sass/layouts/_dark-theme.scss
> +    color: var(--white);
зроби тут var(--bcg-color) краще

2023-02-19 14:03 UTC, snizhanamohyl requested changes
notiflix можна потім реалізувати
ще видали у себе файли з розширенням css, css.map у папці sass, щоб потім не було конфліктів

2023-02-19 18:42 UTC, uvchuk commented on src/favorite.js
> +    getCardsRef();
я мушу їх відстежувати при кожній зміні (додаванні чи видаленні), по іншому не хоче працювати. В глобальні не піде, тому що мені треба саме динамічного стеження по рефах, так як карточки приходять пізніше від того як я починаю стежити за їхніми класами і вішати івент лістенер (ну типу спочатку маю андефайнд, мушу їх відстежити аж після того як все зарендериться)

2023-02-19 18:42 UTC, uvchuk commented on src/favorite.js
> +const savedFavorites = localStorage.getItem('Favorites');
зроблю

2023-02-19 18:42 UTC, uvchuk commented on src/favorite.js
> +    console.log('Saved news cards in favorite: ', favoriteCardsArray.length);
звісно)

2023-02-19 18:42 UTC, uvchuk commented on src/favorite.js
> +    console.log('Failed to markup your favorites news');
+

2023-02-19 18:43 UTC, uvchuk commented on src/js/dark-theme.js
> +const currentTheme = localStorage.getItem('CurrentPageTheme');
ок

2023-02-19 18:43 UTC, uvchuk commented on src/sass/layouts/_dark-theme.scss
> +    color: var(--white);
ок не звернув увагу

2023-02-19 18:47 UTC, uvchuk commented on src/favorite.js
> +    getCardsRef();
вопшем я ше подивлюсь до цього, може получиться якось культурніше це зробити. Мені взагалі якось увесь скрипт прийдеться зробити асинхронним, бо зараз я витягую готову розмітку в html, а коли це все почне тягнутись з бекенду і рендеретись то мені треба буде викликати свої функції аж після завершення цього всього...)

2023-02-21 16:58 UTC, snizhanamohyl approved these changes

2023-02-21 17:07 UTC, merged