add-news-cards-2
snizhanamohyl/team-proj-news-app pull request #3
Opened 2023-02-17 20:06 UTC by VitaliyYakovenko

2023-02-17 22:05 UTC, snizhanamohyl requested changes

2023-02-17 22:05 UTC, snizhanamohyl commented on src/partials/news-cards.html
> +<div class="container">
можна ще додати тег section, наприклад, з класом "news"

2023-02-17 22:05 UTC, snizhanamohyl commented on src/partials/news-cards.html
> +                    <svg width="16" height="16">
svg вже доступні, можеш міняти посилання)

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +.container {
@extend %container;

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +    @media screen and (min-width: 768px) {
@include tablet {}

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +    @media screen and (min-width: 1280px) {
@include desktop {}

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +
додай margin: 20px 16px для desktop, ще перевір за макетом
тоді від'ємний марджин також поміняється для card-set

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +        width: calc((100% - 4 * 23px) / 3);
чому 4 * 23px?

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +        margin-top: 20px;
margin-top: 20px не потрібен, вже є margin-bottom: 20px у img

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +    &__titel {
помилка у назві класу, зміни всюди на title

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +        font-weight: 400;
за замовчуванням у body, має підтягнутися

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +        font-weight: 400;
за замовчуванням у body

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +        font-weight: 400;
за замовчуванням у body

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +        margin-right: 22px;
звідки margin-right: 22px?

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +        padding: 4px 19px;
перевір падінги, наче 4px 8px

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +        right: 21px;
заміни на 20px, то промах дизайнера

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +        margin-left: 6px;
за макетом 4px

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +    &__text {
дублювання коду, знову &__text

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +    &__inform--icon {
дублювання коду, знову &__inform--icon

2023-02-17 22:05 UTC, snizhanamohyl commented on src/sass/layouts/_news-cards.scss
> +    padding-top: 6px;
просто padding: 6px 12px;

2023-02-18 09:12 UTC, VitaliyYakovenko commented on src/partials/news-cards.html
> +<div class="container">
+

2023-02-18 09:12 UTC, VitaliyYakovenko commented on src/partials/news-cards.html
> +                    <svg width="16" height="16">
+

2023-02-18 09:13 UTC, VitaliyYakovenko commented on src/sass/layouts/_news-cards.scss
> +        margin-left: 6px;
+

2023-02-18 09:13 UTC, VitaliyYakovenko commented on src/sass/layouts/_news-cards.scss
> +    &__text {
+

2023-02-18 09:14 UTC, VitaliyYakovenko commented on src/sass/layouts/_news-cards.scss
> +    &__inform--icon {
+

2023-02-18 09:15 UTC, VitaliyYakovenko commented on src/sass/layouts/_news-cards.scss
> +    padding-top: 6px;
+

2023-02-18 09:47 UTC, VitaliyYakovenko commented on src/sass/layouts/_news-cards.scss
> +        right: 21px;
+

2023-02-18 10:27 UTC, snizhanamohyl approved these changes

2023-02-18 10:27 UTC, merged