fix/categories
snizhanamohyl/team-proj-news-app pull request #9
Opened 2023-02-18 18:46 UTC by AlluringUnicorn

Пофіксила баг з кольором, баг з тим що картка закривала дроп даун, додала свгшку, додала підтягування категорій з серверу в кнопки і дроп даун ліст

2023-02-18 23:26 UTC, snizhanamohyl requested changes
файлик categories.js має бути у папці js

2023-02-18 23:26 UTC, snizhanamohyl commented on src/partials/categories.html
> +      <li><button class="dropdown-item" type="button"></button></li>
порожніх лішок в ідеалі бути не повинно, вони мають додаватися через js
і там наче прийшов масив з 50 елементів, відображаються не всі категорії, чи то скрол не працює

2023-02-19 15:13 UTC, AlluringUnicorn commented on src/partials/categories.html
> +      <li><button class="dropdown-item" type="button"></button></li>
Порожні лішки в дропдаун прибрала, а в кнопках це не можливо через кнопку Others яка має бути там першочергово, якщо лишити її там першочергово, а через js рендерити всі інші, то по перше контент при завантаженні дуже скаче, а по друге, інші лішки рендеяться в неправильному порядку, і також деякі лішки мають різні класи для їх додавання/ прибирання на різних ширинах екрану
якщо ж її також рендерити через js, то на фазі парсу коду він не бачить eventlistener на цій кнопці others якої на той момент ще не існує і відмовляється взагалі виконувати " не валідний" код

2023-02-19 19:10 UTC, snizhanamohyl approved these changes

2023-02-19 19:11 UTC, merged